# Generated by Django 4.1.7 on 2025-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='is_id_required',
        ),
        migrations.AddField(
            model_name='companies',
            name='point_total',
            field=models.IntegerField(default=0),
        ),
    ]
