# Generated by Django 4.1.7 on 2025-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companies_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
