# Generated by Django 4.1.7 on 2025-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companies_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='interactive',
            field=models.BooleanField(default=False),
        ),
    ]
